### ISSUE TITLE
PWM and UART support

### ISSUE THREAD

**Issue by matejperejda** [juniorug/libsensorPy#2]
Hello,

I'd like to ask if the library provides support of **PWM** and **UART**.

Thanks.

**Comment by juniorug** [comment]
Hi @matejperejda,

Sorry for the late answer. We have not implemented a UART interface but it's not complex to create one
(see [Serial_port_programming](http://www.elinux.org/Serial_port_programming)). Neither for PWM actuators but is also easy to extend the library and create a concreteActuator like a DC Motor,for example (see [PWM](https://sourceforge.net/p/raspberry-gpio-python/wiki/PWM/)).  
We'll put these on our future features list.
